import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/dist/client/router';

// State
import { useGetBlogsQuery } from '../../features/blog/blogApi';

// Components
import ArticleCard from '../../layouts/ArticleCard';

// Styles
import styles from './styles/home.module.scss';

const Home: NextPage = () => {
  const { pathname, isFallback: routerIsFallBack } = useRouter();

  const result = useGetBlogsQuery();
  const { isLoading, error, data } = result;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article>
        {error ? (
          <>Oh no, there was an error</>
        ) : routerIsFallBack || isLoading ? (
          <>Loading...</>
        ) : data ? (
          data.map((blog) => (
            <Link key={blog.id} href={`${pathname}/${blog.id}`}>
              <ArticleCard title={blog.title} createdAt={blog.id} description={blog.body} />
            </Link>
          ))
        ) : null}
      </article>
    </div>
  );
};

export default Home;
