import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/dist/client/router";

import { useGetBlogsQuery } from "../features/blog/blogApi";
import Header from '../layouts/Header'

import ArticleCard from '../layouts/ArticleCard'


const Home: NextPage = () => {
  const router = useRouter();


  const result = useGetBlogsQuery();
  const { isLoading, error, data } = result;



  return (
    <div className='container' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <article>
       { data && data.map(blog => (
            <ArticleCard key={blog.id} title={blog.title} createdAt={blog.id} description={blog.body} />
       ))}
      </article>
    </div>
  )
}

export default Home
